=== simonovAlexey/masterjava/src/main/resources/fleet.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns="http://javaops.ru"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://javaops.ru"
           elementFormDefault="qualified" attributeFormDefault="unqualified">
<!-- XML Schema generated by QTAssistant/XSD Module (http://www.paschidev.com) -->

    <xs:element name="Fleet" type="FleetType">
        <xs:key name="PK_Cars">
            <xs:selector xpath="Car"/>
            <xs:field xpath="@id"/>
        </xs:key>

        <xs:key name="PK_Trailers">
            <xs:selector xpath="Trailer"/>
            <xs:field xpath="@id"/>
        </xs:key>



        <xs:keyref name="FK_TrailerTruck2Trailers" refer="PK_Trailers">
            <xs:selector xpath="TrailerTruck/Trailer"/>
            <xs:field xpath="@refid"/>
        </xs:keyref>

        <xs:keyref name="FK_TrailerTruck2Cars" refer="PK_Cars">
            <xs:selector xpath="TrailerTruck/Car"/>
            <xs:field xpath="@refid"/>
        </xs:keyref>

    </xs:element>

    <xs:complexType name="FleetType">
        <xs:choice maxOccurs="unbounded">
            <xs:element ref="Car"/>
            <xs:element ref="Trailer"/>
            <xs:element ref="TrailerTruck"/>
        </xs:choice>
    </xs:complexType>

    <!-- SimpleVehicle and ComplexVehicle -->
    <xs:complexType name="SimpleVehicle">
            <xs:sequence minOccurs="0">
                <xs:element name="plate" type="xs:string" minOccurs="1"/>
                <xs:element name="mark" type="xs:string" minOccurs="1"/>
                <xs:element name="model" type="xs:string" minOccurs="1"/>
            </xs:sequence>
                <xs:attribute name="id" type="xs:ID"/>
    </xs:complexType>

    <xs:complexType name="ComplexVehicle">
        <xs:sequence minOccurs="0">
            <xs:element name="plate" type="xs:string" minOccurs="1"/>
            <xs:element name="mark" type="xs:string" minOccurs="1"/>
            <xs:element name="model" type="xs:string" minOccurs="1"/>
        </xs:sequence>
        <xs:attribute name="refid" type="xs:IDREF"/>
    </xs:complexType>


    <!-- Car, Trailer -->

    <xs:element name="Car" type="SimpleVehicle"/>
    <xs:element name="Trailer" type="SimpleVehicle"/>


    <!-- TrailerTruck -->

    <xs:element name="TrailerTruck">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Car" type="ComplexVehicle" minOccurs="1" maxOccurs="1"/>
                <xs:element name="TrailerC" type="ComplexVehicle" minOccurs="1" maxOccurs="1"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== simonovAlexey/masterjava/src/main/resources/feed.xml
<Fleet xmlns="http://javaops.ru"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://javaops.ru fleet.xsd">
    <Car id="car1">
        <plate>AAA</plate>
        <mark>Peugeot</mark>
        <model>206</model>
    </Car>

    <Trailer id="trailer1">
        <plate>EEE</plate>
        <mark>Scania</mark>
        <model>1</model>
    </Trailer>


    <Trailer id="trailer2">
        <plate>EEE2</plate>
        <mark>Scania2</mark>
        <model>2</model>
    </Trailer>



    <TrailerTruck>
        <Car refid="car1"/>
        <TrailerC refid="trailer1"/>
    </TrailerTruck>

    <TrailerTruck>
        <Car refid="car1"/>
        <TrailerC refid="trailer2"/>
    </TrailerTruck>

</Fleet>
