=== simonovAlexey/masterjava/src/main/resources/payload.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://javaops.ru"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://javaops.ru"
           elementFormDefault="qualified" attributeFormDefault="unqualified">

    <xs:element name="Payload">
        <xs:complexType>
            <xs:all>
                <xs:element name="Cities">
                    <xs:complexType>
                        <xs:sequence minOccurs="1" maxOccurs="unbounded">
                            <xs:element ref="City"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Users">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element ref="User"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Projects">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element ref="Project"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Groups">
                    <xs:complexType>
                        <xs:sequence minOccurs="0" maxOccurs="unbounded">
                            <xs:element ref="Group"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:all>
        </xs:complexType>

        <xs:key name="PK_UserGroup">
            <xs:selector xpath="Group"/>
            <xs:field xpath="@id"/>
        </xs:key>
        <xs:keyref name="FK_UserGroup" refer="PK_UserGroup">
            <xs:selector xpath="User/group"/>
            <xs:field xpath="@refid"/>
        </xs:keyref>

        <!--  ___________________PROJECT-GROUP___________________ -->

        <xs:key name="PK_Project">
            <xs:selector xpath="Project"/>
            <xs:field xpath="@id"/>
        </xs:key>
        <xs:keyref name="FK_Group" refer="PK_Project">
            <xs:selector xpath="Group/project"/>
            <xs:field xpath="@id"/>
        </xs:keyref>
    </xs:element>

    <!--  ________________________USER____________________ -->

    <xs:element name="User">
        <xs:complexType>
            <xs:sequence>
                <xs:element type="xs:string" name="email"/>
                <xs:element type="xs:string" name="fullName"/>
                <xs:element type="groupTypeRefID" name="group" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
            <xs:attribute type="flagType" name="flag" use="required"/>
            <xs:attribute type="xs:IDREF" name="city" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="flagType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="active"/>
            <xs:enumeration value="deleted"/>
            <xs:enumeration value="superuser"/>
        </xs:restriction>
    </xs:simpleType>

    <!--  ________________________CITY____________________ -->

    <xs:element name="City" type="cityType"/>

    <xs:complexType name="cityType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:ID" name="id" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <!--  ________________________PROJECT____________________ -->

    <xs:element name="Project" type="projectType"/>

    <xs:complexType name="projectType">
        <xs:sequence maxOccurs="unbounded">
            <xs:element type="xs:string" name="name"/>
            <xs:element type="xs:string" name="description"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID"/>

    </xs:complexType>


    <!--  ________________________GROUP____________________ -->

    <xs:element name="Group" type="groupType"/>

    <!--<xs:complexType name="groupType">
        <xs:simpleContent >
            <xs:extension base="xs:string">
                <xs:attribute type="xs:ID" name="id" use="required"/>

                <xs:attribute type="groupStatusType" name="type"/>
                <xs:attribute type="projectType" name="project"/>
            </xs:extension>

        </xs:simpleContent>
    </xs:complexType>-->

    <xs:complexType name="groupType">
        <xs:complexContent>
            <xs:extension base="baseGroupType">
                <xs:attribute name="id" type="xs:ID"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="groupTypeRefID">
        <xs:complexContent>
            <xs:extension base="baseGroupType">
                <xs:attribute name="refid" type="xs:IDREF"/>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <!--<xs:complexType name="baseGroupType" abstract="true">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="groupStatusType" name="type"/>
                <xs:attribute type="projectType" name="project"/>
            </xs:extension>

        </xs:simpleContent>
    </xs:complexType>-->

    <xs:complexType name="baseGroupType" abstract="true">
        <xs:sequence minOccurs="0">
            <xs:element name="name" type="xs:string" minOccurs="1"/>
        </xs:sequence>
        <xs:attribute type="groupStatusType" name="type"/>
        <xs:attribute type="xs:IDREF" name="project"/>
    </xs:complexType>


    <xs:simpleType name="groupStatusType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="REGISTERING"/>
            <xs:enumeration value="CURRENT"/>
            <xs:enumeration value="FINISHED"/>
        </xs:restriction>
    </xs:simpleType>


</xs:schema>

=== simonovAlexey/masterjava/src/test/resources/payload.xml
<Payload xmlns="http://javaops.ru"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://javaops.ru payload.xsd">

    <Groups>
        <Group id="t12" project="top" type="REGISTERING">
            <name>topjava12</name>
        </Group>
        <Group id="t7" project="top" type="FINISHED">
            <name>topjava7</name>
        </Group>
        <Group id="t8" project="top" type="FINISHED">
            <name>topjava8</name>
        </Group>
        <Group id="t9" project="top" type="FINISHED">
            <name>topjava9</name>
        </Group>
        <Group id="t11" project="top" type="CURRENT">
            <name>topjava11</name>
        </Group>

        <Group id="m2" project="master" type="CURRENT">
            <name>masterjava2</name>
        </Group>
        <Group id="m3" project="master" type="REGISTERING">
            <name>masterjava3</name>
        </Group>
        <Group id="m1" project="master" type="FINISHED">
            <name>masterjava1</name>
        </Group>
    </Groups>

    <Projects>
        <Project id="top">
            <group type="FINISHED">topjava7</group>
            <name>topJava</name>
            <description>Описание ТОПджава</description>
        </Project>
        <Project id="master">
            <name>masterJava</name>
            <description>Описание МАСТЕРджава</description>
        </Project>
    </Projects>

    <Users>
        <User flag="active" city="kiv">
            <email>gmail@gmail.com</email>
            <fullName>Full Name</fullName>
            <group refid="m2"/>
            <group refid="t8"/>
        </User>

        <User flag="superuser" city="spb">
            <email>admin@javaops.ru</email>
            <fullName>Admin</fullName>
            <group refid="m1"/>
        </User>

        <User flag="deleted" city="spb">
            <email>mail@yandex.ru</email>
            <fullName>Deleted</fullName>
            <group refid="t7"/>
            <group refid="m3"/>
        </User>
    </Users>

    <Cities>
        <City id="spb">Санкт-Петербург</City>
        <City id="kiv">Киев</City>
        <City id="mnsk">Минск</City>
    </Cities>

</Payload>
